import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Clock, MapPin, UtensilsCrossed } from 'lucide-react-native';
import { useAuth } from '@/lib/auth';
import { FoodDonation, Profile, supabase } from '@/lib/supabase';
import { colors, radius, spacing, typography } from '@/lib/theme';
import { getFoodImages, resolveFoodImages } from '@/lib/foodImages';

export default function FoodDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { t, language } = useAuth(); const font = language === 'ar' ? 'Cairo-' : 'Inter-';
  const [meal, setMeal] = useState<FoodDonation | null>(null); const [owner, setOwner] = useState<Profile | null>(null);
  useEffect(() => { if (!id) return; void supabase.from('food_donations').select('*').eq('id', id).maybeSingle().then(async ({ data }) => { if (!data) return; const resolved = await resolveFoodImages(data as FoodDonation); setMeal(resolved); const result = await supabase.from('public_profiles').select('*').eq('id', resolved.user_id).maybeSingle(); setOwner(result.data as Profile | null); }); }, [id]);
  return <SafeAreaView style={styles.container}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={styles.arrow}>{language === 'ar' ? '›' : '‹'}</Text></TouchableOpacity><Text style={[typography.heading, { color: colors.brown, fontFamily: `${font}Bold` }]}>{t('mealDetails')}</Text></View>{!meal ? <ActivityIndicator color={colors.primary} style={{ marginTop: spacing.xl }} /> : <ScrollView contentContainerStyle={styles.content}>{getFoodImages(meal).length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: spacing.sm }}>{getFoodImages(meal).map((uri, index) => <Image key={`${uri}-${index}`} source={{ uri }} style={styles.image} />)}</ScrollView> : <View style={[styles.image, styles.fallback]}><UtensilsCrossed size={46} color={colors.green} /></View>}<Text style={[typography.title, { color: colors.brown, fontFamily: `${font}Bold` }]}>{meal.food_name}</Text><Text style={[typography.body, { color: colors.brownMuted, fontFamily: `${font}Regular` }]}>{meal.description}</Text><View style={styles.row}><Text>🍱 {meal.meals} {t('meals')}</Text><View style={styles.meta}><Clock size={15} color={colors.goldenDark} /><Text>{new Date(meal.expires_at).toLocaleString(language === 'ar' ? 'ar-AE' : 'en-AE')}</Text></View><View style={styles.meta}><MapPin size={15} color={colors.green} /><Text>{meal.latitude.toFixed(3)}, {meal.longitude.toFixed(3)}</Text></View></View><TouchableOpacity style={styles.owner} onPress={() => router.push({ pathname: '/user-profile' as any, params: { id: meal.user_id } })}>{owner?.avatar_url && <Image source={{ uri: owner.avatar_url }} style={styles.avatar} />}<Text style={[typography.bodyBold, { color: colors.brown, fontFamily: `${font}Bold` }]}>{owner?.full_name ?? t('sharekHelper')}</Text></TouchableOpacity></ScrollView>}</SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, arrow: { fontSize: 36, color: colors.brown }, content: { padding: spacing.lg, gap: spacing.md }, image: { width: 300, height: 220, borderRadius: radius.lg }, fallback: { backgroundColor: colors.surfaceAlt, alignItems: 'center', justifyContent: 'center' }, row: { gap: spacing.sm, backgroundColor: colors.surface, padding: spacing.md, borderRadius: radius.md }, meta: { flexDirection: 'row', alignItems: 'center', gap: 5 }, owner: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, padding: spacing.md, borderRadius: radius.md }, avatar: { width: 42, height: 42, borderRadius: 21 } });
