import React, { useState } from 'react';
import { ActivityIndicator, Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenHeader } from '@/components/ScreenHeader';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { colors, radius, spacing, typography } from '@/lib/theme';
export default function ReportProblem() { const { session, language } = useAuth(); const [text, setText] = useState(''); const [busy, setBusy] = useState(false); const ar = language === 'ar'; const submit = async () => { if (!text.trim() || !session?.user) return; setBusy(true); const { error } = await supabase.from('user_reports').insert({ reporter_id: session.user.id, category: 'other', description: text.trim() }); setBusy(false); if (error) Alert.alert(ar ? 'تعذر إرسال البلاغ' : 'Could not send report'); else { Alert.alert(ar ? 'تم إرسال البلاغ' : 'Report sent'); router.back(); } }; return <View style={styles.container}><ScreenHeader title={ar ? 'الإبلاغ عن مشكلة' : 'Report a problem'} onBack={() => router.back()} /><View style={styles.card}><Text style={styles.help}>{ar ? 'اكتب تفاصيل المشكلة أو السلوك غير المناسب وسيراجعه فريق الإدارة.' : 'Describe the problem or inappropriate behavior. The admin team will review it.'}</Text><TextInput multiline value={text} onChangeText={setText} style={styles.input} placeholder={ar ? 'اكتب البلاغ هنا...' : 'Describe the issue...'} placeholderTextColor={colors.brownMuted} /><TouchableOpacity style={styles.button} onPress={submit} disabled={busy}>{busy ? <ActivityIndicator color={colors.white} /> : <Text style={styles.buttonText}>{ar ? 'إرسال البلاغ' : 'Send report'}</Text>}</TouchableOpacity></View></View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, card: { margin: spacing.lg, backgroundColor: colors.surface, padding: spacing.lg, borderRadius: radius.lg, gap: spacing.md }, help: { ...typography.body, color: colors.brownMuted }, input: { minHeight: 150, textAlignVertical: 'top', ...typography.body, color: colors.brown, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md }, button: { backgroundColor: colors.primary, borderRadius: radius.md, padding: spacing.md, alignItems: 'center' }, buttonText: { ...typography.bodyBold, color: colors.white } });
